// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_RyrbOlp9Yvykf75en7BBeCCxswKhr9I',
    appId: '1:214208815474:web:25a5e47eebb433e29d3deb',
    messagingSenderId: '214208815474',
    projectId: 'basededadeslogin',
    authDomain: 'basededadeslogin.firebaseapp.com',
    storageBucket: 'basededadeslogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHfOkwqkOXF2uekBsLh89ESrhKrUGtZKA',
    appId: '1:214208815474:android:1d7c18278761a9cf9d3deb',
    messagingSenderId: '214208815474',
    projectId: 'basededadeslogin',
    storageBucket: 'basededadeslogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFasWUNa-J8OYAM9McxoDlpBhkyY7veU',
    appId: '1:214208815474:ios:c0c79f39ef54efe89d3deb',
    messagingSenderId: '214208815474',
    projectId: 'basededadeslogin',
    storageBucket: 'basededadeslogin.appspot.com',
    iosBundleId: 'com.example.flutterFirebase202324',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLFasWUNa-J8OYAM9McxoDlpBhkyY7veU',
    appId: '1:214208815474:ios:7288fc11736175a69d3deb',
    messagingSenderId: '214208815474',
    projectId: 'basededadeslogin',
    storageBucket: 'basededadeslogin.appspot.com',
    iosBundleId: 'com.example.flutterFirebase202324.RunnerTests',
  );
}
